<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [ ]:
!pip install sqlalchemy==1.3.9

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
%pip install ipython-sql

Defaulting to user installation because normal site-packages is not writeable
Collecting ipython-sql
  Obtaining dependency information for ipython-sql from https://files.pythonhosted.org/packages/30/8f/9e50fa53ffc371483f9d1b90c1175b706d28a2e978e90a8894035af01905/ipython_sql-0.5.0-py3-none-any.whl.metadata
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Obtaining dependency information for prettytable from https://files.pythonhosted.org/packages/d9/5a/bfdc26c0e19156992b1dc9de47f0b2e8992fe43db9981d814f860bdce2b3/prettytable-3.11.0-py3-none-any.whl.metadata
  Downloading prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: ipython in c:\programdata\anaconda3\lib\site-packages (from ipython-sql) (8.15.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Obtaining dependency information for sqlalchemy>=2.0 from https://files.pythonhosted.org/packages/b1/03/d12b7c1d36fd80150c1d52e121614cf9377dac99e5497af8d8f5b2a8db64/SQLAlchemy-2.0.36-cp311-cp311-win_amd64.whl.metadata
  Downloading SQLAlchemy-2.0.36-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting sqlparse (from ipython-sql)
  Obtaining dependency information for sqlparse from https://files.pythonhosted.org/packages/5d/a5/b2860373aa8de1e626b2bdfdd6df4355f0565b47e51f7d0c54fe70faf8fe/sqlparse-0.5.1-py3-none-any.whl.metadata
  Downloading sqlparse-0.5.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\programdata\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\samuel.santos\appdata\roaming\python\python311\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (2.0.1)
Requirement already satisfied: backcall in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in c:\users\samuel.santos\appdata\roaming\python\python311\site-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading SQLAlchemy-2.0.36-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 660.6 kB/s eta 0:00:04
   - -------------------------------------- 0.1/2.1 MB 656.4 kB/s eta 0:00:04
   - -------------------------------------- 0.1/2.1 MB 585.1 kB/s eta 0:00:04
   - -------------------------------------- 0.1/2.1 MB 535.8 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/2.1 MB 568.9 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/2.1 MB 568.9 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.1 MB 557.9 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.1 MB 541.9 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.1 MB 529.7 kB/s eta 0:00:04
   ---- ----------------------------------- 0.3/2.1 MB 524.0 kB/s eta 0:00:04
   ----- ---------------------------------- 0.3/2.1 MB 497.1 kB/s eta 0:00:04
   ----- ---------------------------------- 0.3/2.1 MB 520.7 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.1 MB 517.2 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.1 MB 512.0 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.1 MB 502.9 kB/s eta 0:00:04
   ------- -------------------------------- 0.4/2.1 MB 516.2 kB/s eta 0:00:04
   ------- -------------------------------- 0.4/2.1 MB 508.7 kB/s eta 0:00:04
   -------- ------------------------------- 0.4/2.1 MB 507.1 kB/s eta 0:00:04
   -------- ------------------------------- 0.5/2.1 MB 512.6 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.1 MB 526.6 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.1 MB 517.8 kB/s eta 0:00:04
   ---------- ----------------------------- 0.5/2.1 MB 522.2 kB/s eta 0:00:03
   ---------- ----------------------------- 0.6/2.1 MB 518.4 kB/s eta 0:00:03
   ---------- ----------------------------- 0.6/2.1 MB 512.9 kB/s eta 0:00:03
   ----------- ---------------------------- 0.6/2.1 MB 509.7 kB/s eta 0:00:03
   ----------- ---------------------------- 0.6/2.1 MB 515.5 kB/s eta 0:00:03
   ------------ --------------------------- 0.6/2.1 MB 512.4 kB/s eta 0:00:03
   ------------ --------------------------- 0.7/2.1 MB 518.1 kB/s eta 0:00:03
   ------------ --------------------------- 0.7/2.1 MB 513.2 kB/s eta 0:00:03
   ------------- -------------------------- 0.7/2.1 MB 510.5 kB/s eta 0:00:03
   ------------- -------------------------- 0.7/2.1 MB 513.9 kB/s eta 0:00:03
   ------------- -------------------------- 0.7/2.1 MB 504.1 kB/s eta 0:00:03
   -------------- ------------------------- 0.7/2.1 MB 513.1 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 503.7 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 501.6 kB/s eta 0:00:03
   --------------- ------------------------ 0.8/2.1 MB 496.4 kB/s eta 0:00:03
   --------------- ------------------------ 0.8/2.1 MB 494.7 kB/s eta 0:00:03
   ---------------- ----------------------- 0.8/2.1 MB 496.1 kB/s eta 0:00:03
   ---------------- ----------------------- 0.9/2.1 MB 494.4 kB/s eta 0:00:03
   ----------------- ---------------------- 0.9/2.1 MB 494.5 kB/s eta 0:00:03
   ----------------- ---------------------- 0.9/2.1 MB 494.5 kB/s eta 0:00:03
   ----------------- ---------------------- 0.9/2.1 MB 484.7 kB/s eta 0:00:03
   ------------------ --------------------- 0.9/2.1 MB 488.9 kB/s eta 0:00:03
   ------------------ --------------------- 1.0/2.1 MB 487.6 kB/s eta 0:00:03
   ------------------ --------------------- 1.0/2.1 MB 481.3 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 480.2 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 480.2 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 471.0 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 470.2 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 472.9 kB/s eta 0:00:03
   -------------------- ------------------- 1.1/2.1 MB 467.5 kB/s eta 0:00:03
   -------------------- ------------------- 1.1/2.1 MB 466.9 kB/s eta 0:00:03
   -------------------- ------------------- 1.1/2.1 MB 466.9 kB/s eta 0:00:03
   -------------------- ------------------- 1.1/2.1 MB 455.8 kB/s eta 0:00:03
   --------------------- ------------------ 1.1/2.1 MB 458.0 kB/s eta 0:00:03
   --------------------- ------------------ 1.1/2.1 MB 458.0 kB/s eta 0:00:03
   --------------------- ------------------ 1.1/2.1 MB 447.9 kB/s eta 0:00:03
   --------------------- ------------------ 1.1/2.1 MB 447.9 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 442.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 442.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 433.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 433.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 425.9 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.1 MB 425.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 421.3 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 421.3 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 421.3 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 421.3 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 398.7 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 397.2 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 397.2 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 397.2 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 384.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 384.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 384.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.2/2.1 MB 384.9 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 369.8 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 369.8 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 369.8 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 369.8 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 357.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 357.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 357.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 348.4 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 348.4 kB/s eta 0:00:03
   ------------------------- -------------- 1.3/2.1 MB 346.7 kB/s eta 0:00:03
   ------------------------- -------------- 1.3/2.1 MB 340.9 kB/s eta 0:00:03
   ------------------------- -------------- 1.3/2.1 MB 340.9 kB/s eta 0:00:03
   ------------------------- -------------- 1.4/2.1 MB 340.7 kB/s eta 0:00:03
   ------------------------- -------------- 1.4/2.1 MB 340.7 kB/s eta 0:00:03
   -------------------------- ------------- 1.4/2.1 MB 339.2 kB/s eta 0:00:03
   -------------------------- ------------- 1.4/2.1 MB 336.5 kB/s eta 0:00:03
   -------------------------- ------------- 1.4/2.1 MB 337.6 kB/s eta 0:00:03
   -------------------------- ------------- 1.4/2.1 MB 337.6 kB/s eta 0:00:03
   --------------------------- ------------ 1.4/2.1 MB 335.1 kB/s eta 0:00:03
   --------------------------- ------------ 1.4/2.1 MB 336.2 kB/s eta 0:00:02
   --------------------------- ------------ 1.5/2.1 MB 337.3 kB/s eta 0:00:02
   ---------------------------- ----------- 1.5/2.1 MB 334.7 kB/s eta 0:00:02
   ---------------------------- ----------- 1.5/2.1 MB 334.7 kB/s eta 0:00:02
   ---------------------------- ----------- 1.5/2.1 MB 334.7 kB/s eta 0:00:02
   ----------------------------- ---------- 1.5/2.1 MB 334.5 kB/s eta 0:00:02
   ----------------------------- ---------- 1.5/2.1 MB 334.5 kB/s eta 0:00:02
   ----------------------------- ---------- 1.5/2.1 MB 331.0 kB/s eta 0:00:02
   ----------------------------- ---------- 1.5/2.1 MB 333.3 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 334.3 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.1 MB 332.0 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.1 MB 333.1 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.1 MB 333.0 kB/s eta 0:00:02
   ------------------------------- -------- 1.6/2.1 MB 335.1 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.1 MB 336.0 kB/s eta 0:00:02
   -------------------------------- ------- 1.7/2.1 MB 338.1 kB/s eta 0:00:02
   -------------------------------- ------- 1.7/2.1 MB 335.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.7/2.1 MB 339.0 kB/s eta 0:00:02
   --------------------------------- ------ 1.7/2.1 MB 338.8 kB/s eta 0:00:02
   --------------------------------- ------ 1.7/2.1 MB 338.7 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.1 MB 338.6 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.1 MB 338.6 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.1 MB 336.5 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 335.4 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 335.4 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 334.4 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 332.4 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 332.4 kB/s eta 0:00:01
   ----------------------------------- ---- 1.8/2.1 MB 332.4 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.1 MB 330.4 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.1 MB 331.3 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 331.3 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 331.2 kB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 332.2 kB/s eta 0:00:01
   ------------------------------------- -- 1.9/2.1 MB 331.2 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 332.9 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 333.8 kB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 334.5 kB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 333.7 kB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 333.7 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 336.1 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 336.0 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 336.1 kB/s eta 0:00:00
Downloading prettytable-3.11.0-py3-none-any.whl (28 kB)
Downloading sqlparse-0.5.1-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/44.2 kB ? eta -:--:--
   --------- ------------------------------ 10.2/44.2 kB ? eta -:--:--
   --------------------------- ------------ 30.7/44.2 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 44.2/44.2 kB 547.0 kB/s eta 0:00:00
Installing collected packages: sqlparse, sqlalchemy, prettytable, ipython-sql
Successfully installed ipython-sql-0.5.0 prettytable-3.11.0 sqlalchemy-2.0.36 sqlparse-0.5.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script sqlformat.exe is installed in 'C:\Users\samuel.santos\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [3]:
%load_ext sql

In [4]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [ ]:
!pip install -q pandas

In [5]:
%sql sqlite:///my_data1.db

In [6]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

**Note:This below code is added to remove blank rows from table**

In [7]:
#DROP THE TABLE IF EXISTS

%sql DROP TABLE IF EXISTS SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[]

In [8]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [9]:
%sql SELECT DISTINCT "Launch_Site" FROM SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[('CCAFS LC-40',), ('VAFB SLC-4E',), ('KSC LC-39A',), ('CCAFS SLC-40',)]


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [10]:
%sql SELECT * FROM SPACEXTABLE WHERE "Launch_Site" LIKE 'CCA%' LIMIT 5;

 * sqlite:///my_data1.db
Done.

[('2010-06-04', '18:45:00', 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)'),
 ('2010-12-08', '15:43:00', 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)'),
 ('2012-05-22', '7:44:00', 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt'),
 ('2012-10-08', '0:35:00', 'F9 v1.0  B0006', 'CCAFS LC-40', 'SpaceX CRS-1', 500, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 ('2013-03-01', '15:10:00', 'F9 v1.0  B0007', 'CCAFS LC-40', 'SpaceX CRS-2', 677, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt')]

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [11]:
%sql SELECT SUM("Payload_Mass__kg_") AS Total_Payload_Mass FROM SPACEXTABLE WHERE "Customer" = 'NASA (CRS)';

 * sqlite:///my_data1.db
Done.

[(45596,)]

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [12]:
%sql SELECT AVG("Payload_Mass__kg_") AS Average_Payload_Mass FROM SPACEXTABLE WHERE "Booster_Version" = 'F9 v1.1';

 * sqlite:///my_data1.db
Done.

[(2928.4,)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [13]:
%sql SELECT MIN(Date) AS First_Successful_Landing FROM SPACEXTABLE WHERE "Landing_Outcome" = 'True RTLS';

 * sqlite:///my_data1.db
Done.

[(None,)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [14]:
%sql SELECT "Booster_Version" FROM SPACEXTABLE WHERE "Landing_Outcome" = 'True ASDS' AND "Payload_Mass__kg_" > 4000 AND "Payload_Mass__kg_" < 6000;

 * sqlite:///my_data1.db
Done.

[]

### Task 7




##### List the total number of successful and failure mission outcomes

In [15]:
%sql SELECT "Landing_Outcome", COUNT(*) AS Total FROM SPACEXTABLE GROUP BY "Landing_Outcome";

 * sqlite:///my_data1.db
Done.

[('Controlled (ocean)', 5),
 ('Failure', 3),
 ('Failure (drone ship)', 5),
 ('Failure (parachute)', 2),
 ('No attempt', 21),
 ('No attempt ', 1),
 ('Precluded (drone ship)', 1),
 ('Success', 38),
 ('Success (drone ship)', 14),
 ('Success (ground pad)', 9),
 ('Uncontrolled (ocean)', 2)]

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [17]:
%%sql
SELECT "Booster_Version"
FROM SPACEXTABLE
WHERE "Payload_Mass__kg_" = (
    SELECT MAX("Payload_Mass__kg_") FROM SPACEXTABLE
);

 * sqlite:///my_data1.db
Done.

[('F9 B5 B1048.4',),
 ('F9 B5 B1049.4',),
 ('F9 B5 B1051.3',),
 ('F9 B5 B1056.4',),
 ('F9 B5 B1048.5',),
 ('F9 B5 B1051.4',),
 ('F9 B5 B1049.5',),
 ('F9 B5 B1060.2 ',),
 ('F9 B5 B1058.3 ',),
 ('F9 B5 B1051.6',),
 ('F9 B5 B1060.3',),
 ('F9 B5 B1049.7 ',)]

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [18]:
%%sql
SELECT 
    substr(Date, 6, 2) AS Month, 
    "Landing_Outcome", 
    "Booster_Version", 
    "Launch_Site"
FROM SPACEXTABLE
WHERE 
    "Landing_Outcome" = 'False ASDS'
    AND substr(Date, 0, 5) = '2015';

 * sqlite:///my_data1.db
Done.

[]

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [19]:
%%sql
SELECT 
    "Landing_Outcome", 
    COUNT(*) AS Outcome_Count
FROM SPACEXTABLE
WHERE 
    Date BETWEEN '2010-06-04' AND '2017-03-20'
GROUP BY "Landing_Outcome"
ORDER BY Outcome_Count DESC;

 * sqlite:///my_data1.db
Done.

[('No attempt', 10),
 ('Success (drone ship)', 5),
 ('Failure (drone ship)', 5),
 ('Success (ground pad)', 3),
 ('Controlled (ocean)', 3),
 ('Uncontrolled (ocean)', 2),
 ('Failure (parachute)', 2),
 ('Precluded (drone ship)', 1)]

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

<!--
## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2024-07-10 | 1.1 |Anita Verma | Changed Version|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |
-->

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>